force-app/main/default/objects/AsyncRequest__c/AsyncRequest__c.object-meta.xml
<CustomObject>
    <label>Async Request</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Async Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AsyncRequest__c/fields/Params__c.field-meta.xml
<CustomField>
    <fullName>Params__c</fullName>
    <label>Params</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/AsyncProcessors/AsyncExchangeJob.cls
/*********************************************************************************
Class Name      : AsyncExchangeJob
Description     : Async Job class used for the exchange app as instance used in factory and strategy pattern
Created By      : Sebastian Torres
Created Date    : 2021-07-13  
Modification Log: 
---------------------------------------------------------------------------------- 
Developer                   Date                   Description
----------------------------------------------------------------------------------
Sebastian                 2021-07-13               Initial version
*********************************************************************************/
public class AsyncExchangeJob extends AsyncJob {
    
    public override void executeAsyncProcess(AsyncRequest__c request) 
    {
        //Checking limits
        if(!limitsAvailable()) return;
        
        List<ID> idsAfterSplit = request.Params__c.split(',');
        Integer allowedCallouts = Limits.getLimitCallouts() - Limits.getCallouts();
        Set<Id> oppIds = new Set<Id>();
        for(Opportunity opp:new OpportunitiesSelector().selectByIdForCallouts(idsAfterSplit, allowedCallouts)) {
                  oppIds.add(opp.id);       
        } 
       ExchangeService.applyExchangeRatesinOpps(oppIds);
    } 
    
    

}